// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import OwlCarousselController from "./owl_caroussel_controller.js"
application.register("owl-caroussel", OwlCarousselController)

import WowjsController from "./wowjs_controller.js"
application.register("wowjs", WowjsController)
